### ISSUE TITLE
Request: Feature to remove traces without requiring re-fixing

### ISSUE THREAD

**Issue by johnyradio** [bblanchon/ArduinoTrace#6]
Your video 12:57 shows you retyping the fix after tracing it. you just did your bug-fix TWICE. Too much work, and what if you forget the fix? What if the fix is many small changes? Please add feature to remove dumps and traces automatically, instead of programmer having to revert and then retype their fix. thx!

**Comment by bblanchon** [comment]
Hi @johnyradio,

I respect your opinion, but I believe that clean code mustn't contain any traces; that's why I remove all the traces before committing.
Traces are just a diagnostic tool that I use temporarily.

How does this request differ from #7?

Best regards,
Benoit

**Comment by johnyradio** [comment]
Hi Benoit

**First concern** is reducing effort, and eliminating duplication of effort.

In your video, you're duplicating effort. With your traces in place, you
applied the bug-fix.

Then in order to remove the traces, you revert. Reverting ALSO removes
your bug-fix.

Then you reapplied the same bug-fix a SECOND TIME. That's duplication of
effort.

Ideally, you can find a way to remove the traces without removing the
bug-fix.

I see a few solutions:

- a simple manual search-and-replace, which replaces all the traces with
nothing. If possible, include the linefeed in the search.

- a macro which automates the same search-and-replace

Thx!

**Comment by johnyradio** [comment]
**Second issue** is: What if the programmer wants to COMPILE without the
traces, but KEEP using the traces for debugging purposes? Ideas:

- search-and-replace to a NEW TEMPORARY FILE, and compile that new file.
(Don't even need to save it to disk).

- a pre-compiler which strips out the traces before compiling.

Ideally, Always compile without traces.

Cheers!

**Comment by bblanchon** [comment]
As I said on #7, you can define `ARDUINOTRACE_ENABLE` to `0`.

**Comment by johnyradio** [comment]
ARDUINOTRACE_ENABLE to 0 will compile without traces?

**Comment by bblanchon** [comment]
Exactly.

**Comment by johnyradio** [comment]
Then why did you revert, in the video?
thx

**Comment by bblanchon** [comment]
As I already told you, I believe that clean code mustn't contain any debug code.
Traces are just a temporary diagnostic tool.

**Comment by johnyradio** [comment]
In your video, you did the following:

1. added trace code
2. applied the fix
3. reverted
4. _re-applied_ the same fix that you did in Step #2, above. 

Correct?
